# Deloppgave 4: Studiedesign

## Introduction

Foam rolling is a tool used by many to help with the recovery process after physical activity and to help against the resulting muscle damage. MacDonald et al. [-@macdonald2014] designed a study to determine if foam rolling could help with the recovery after intense exercise which induced delayed onset muscle soreness (DOMS) and the potential underlying mechanisms. They used a resistance training protocol, whereas D'Amico & Gillis [-@damico2019] wanted to look at the effect of foam rolling on exercise-induced muscle damage (EIMD) following a sprinting session. Their hypothesis was that foam rolling after EIMD would reduce the impairment for agility, joint range of motion (ROM) and vertical jump. Another study has been done on professional soccer players to examine if foam rolling was an effective recovery tool after a soccer specific training session [@rey2019]. Focus was put on ROM, vertical jump, sprint, agility, perception of recovery and muscle soreness. The hypothesis they came up with was that foam rolling would have bigger recovery-related effects than not doing so. Pearcey et al. [-@pearcey2015] chose to look at the effects of foam rolling as a form of recovery after a mix of resistance training and sprinting. They examined the influence of foam rolling on sprint time, power, change of direction etc. Romero-Moraleda et al. [-@romero-moraleda2019] tried to see if using non-vibrating (NVFR) vs. vibrating (VFR) foam rollers after intense exercise resulted in different effects on recovery. Parameters were muscle oxygen saturation (SmO~2~), vertical jump, counter movement jump (CMJ), ROM in hip and knee and perceived pain.

## Method

#### Participants

MacDonald et al. [-@macdonald2014] had male participants (n = 20) who were used to resistance training and trained regularly. They were split into two groups randomly, the foam rolling (n = 10) and control (n = 10) group. D'Amico & Gillis et al. [-@damico2019] performed their study on male participants as well. 18 participants were in the foam rolling group and 19 in the control group, which did not foam roll before testing. 18 professional male soccer players participated in the study of Rey et al. [-@rey2019] and were put into either the foam rolling (n = 9) or control (n = 9) group randomly. 8 university students who were experienced in resistance training, volunteered for the study of Pearcey et al. [-@pearcey2015]. Romero-Moraleda et al. [-@romero-moraleda2019] performed a pilot study with 5 participants per group first. Building on information from the pilot study they chose to have 38 healthy and active participiants (32 men, 6 women). The participants were randomly assigned to the VFR or NVFR group.

#### Study design

All studies were (randomized) controlled trials. A benefit of choosing this kind of study design is that one doesn't need too many subjects to get a lot of information. The subjects are put into groups randomly, where one group acts as the control group [@designin2013]. In the studies mentioned in this report, the control groups where the ones not using foam rolling as a recovery tool, or in one case only using non-vibration foam rollers. The only difference in the above mentioned studies was that 4 of them used two groups with different subjects to examine the effects of foam rolling on recovery and one study chose to let all participants perform both conditions (foam rolling, no foam rolling) with a 4 week separation.

#### Intervention

All participants of the MacDonald et al. [-@macdonald2014] study completed the same protocol for testing, which was done 5 times with the testing sessions conducted at the same time of day each time. The foam rolling group added a 20 minute foam rolling session after each testing session. The 37 participants of D'Amico & Gillis et al. [-@damico2019] followed a sprinting protocol (40 x 15 meters) to induce muscle damage. Straight after the sprinting session and on the 4 following days the different parameters were measured (ROM, vertical jump, agility). One group did a foam rolling session before each testing session, whereas the control group did not. The professional soccer players in the study of Rey et al. [-@rey2019] followed the same training routine. One group performed 20 minutes of foam rolling after the training session, while the control group had a 20 minute long passive recovery (sit on bench). The soccer players had a first experimental session to collect pre-test data, followed by a standardized training session, after which they either did or did not foam roll. The second experimental session was used to collect post-test data. Pearcey et al. [-@pearcey2015] had an intervention split into two parts with a 4 week break in between. Participants performed resistance training which was either followed by 20 minutes of foam rolling immediately, after 24 and after 48 hours, or not followed by foam rolling. The main measures were pressure-pain threshold, strength-endurance and sprint time. Romero-Moraleda et al. [-@romero-moraleda2019] induced muscle damage by letting all the participants perform a 10x10 squat protocol. 48 hours after that the first round of measurements (SmO~2~, vertical jump, counter movement jump (CMJ), hip & knee ROM and perceived pain) was taken. Straight after the first round each group performed their foam rolling protocol (NVFR vs. VFR), followed by the second round of measurements.

#### Statistical analysis

MacDonald et al. [-@macdonald2014] and Pearcey et al. [-@pearcey2015] used magnitude-based inferences and precision of estimation for their data analyses, which help make decisions based on confidence intervals. D'Amico & Gillis et al. [-@damico2019] checked all data for normality of distribution (Kolmogorov-Smirnov test). A 2-tailed independent t-test was used on the normally distributed data and a 2-tailed Mann-Whitney U-test on the not normally distributed data (alpha level set at 0.05). Rey et al. [-@rey2019] distributed all variables normally and performed a repeated-measures analysis of variance calculation for each parameter. Romero-Moraleda et al. [-@romero-moraleda2019] used ANOVA to compare the results from the different tests (baseline, pre- and post-treatment) with P-values lower than 0.05 seen as statistically significant.

## Results

Muscle soreness lessened at all time points with the help of foam rolling while ROM improved as well. Foam rolling also improved muscle activation at all time points and the performance in the vertical jump after at POST -48 [@macdonald2014]. Most tested parameters (soreness, ROM, vertical jump) showed no significant difference between the foam rolling and control group, while agility was better in the foam rolling group [@damico2019]. The results from the study of Rey et al. [-@rey2019] show that it is helpful to foam roll when trying to improve recovery in agility as well as to lessen perceived muscle soreness. Pearcey et al. [-@pearcey2015] found that foam rolling helped with improving muscle tenderness in the days following the training protocol. Sprint time, power and strength-endurance improved as well. The results of Romero-Moraleda et al. [-@romero-moraleda2019] showed that the VFR group had greater improvements in hip joint ROM than the NVFR group, while both groups had the same benefits in the improvement of pressure pain threshold, knee joint ROM and SmO~2~.

## Conclusion

Compared to the control group, muscle soreness, vertical jump height, ROM and muscle activation improved in the foam rolling group [@macdonald2014]. The findings of D'Amico & Gillis [-@damico2019] show that foam rolling can speed up the recovery of agility after EIMD caused by sprinting and makes it a helpful tool for athletes who have to recover quickly in that aspect. Based on the results found by Rey et al. [-@rey2019] they conclude that professional soccer players benefit from 15 to 20 minutes of foam rolling after a training session. Foam rolling can lessen DOMS effectively, according to Pearcey et al. [-@pearcey2015]. The findings of Romero-Moraleda et al. [-@romero-moraleda2019] suggest that hip joint ROM could be improved and perceived pain could be reduced even more with the help of VFR compared to NVFR.

I think using (randomized) controlled trials as a study design works well for this kind of research. This kind of study design might be limiting in other research fields but is sufficient in the cases mentioned here. The goal was to determine if foam rolling could help with the recovery process, so being able to study one outcome is enough. The groups were assigned randomly so bias shouldn't play too much of a role here either. I think however that I would choose the 2 group design, and not follow the set-up of the one study that used the same subjects and tested both conditions on all subjects.
